# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Submit a new internal testing version to the Play store"
  lane :internal do
    gradle(
      task: "clean bundle",
      build_type: "ghostery"
    )
    upload_to_play_store(
      apk_paths:ENV["GRADLE_ALL_APK_OUTPUT_PATHS"],
      track: 'internal',
      skip_upload_metadata: true,
      skip_upload_images: true,
      skip_upload_changelogs: true,
      changes_not_sent_for_review: true,
      skip_upload_screenshots: true,)
  end
end
